ReservationSystem.UI/Controllers/OwnerAssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationSystem.DATA.EF;
using Microsoft.AspNet.Identity;
using IdentitySample.Models;
using System.Drawing;
using ReservationSystem.DATA.EF.Services;

namespace ReservationSystem.UI.Controllers
{
    public class MyAuthorize : AuthorizeAttribute
    {
        private ReservationSystemEntities db = new ReservationSystemEntities();

        protected override bool AuthorizeCore(HttpContextBase httpContext)
        {
            var authorized = base.AuthorizeCore(httpContext);
            if (!authorized)
            {
                return false;
            }
            var rd = httpContext.Request.RequestContext.RouteData;
            var id = rd.Values["id"];
            var userName = httpContext.User.Identity.Name;
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            UserDetail user = db.UserDetails.Find(userName);
            return ownerAsset.OwnerID == user.UserID;
        }
    }
    public class OwnerAssetsController : Controller
    {
        
        private ReservationSystemEntities db = new ReservationSystemEntities();

        // GET: OwnerAssets
        [Authorize]
        public ActionResult Index()
        {
            var teamlist = db.OwnerAssets.ToList().Where(x => x.OwnerID == User.Identity.GetUserId());

            return View(teamlist);
        }
        [Authorize(Roles ="Admin, Employee")]
        public ActionResult AdminIndex()
        {
            return View(db.OwnerAssets.ToList());
        }

        // GET: OwnerAssets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }
        [Authorize]
        // GET: OwnerAssets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OwnerAssets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "OwnerAssetID,AssetName,OwnerID,AssetPhoto,SpecialNotes,IsActive,DateAdded")] OwnerAsset ownerAsset, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                #region File Upload using Image Service
                string imageName = "noimage.png";//default image filename

                if (imageUpload != null)
                {
                    //process the image upload if it exists...
                    imageName = imageUpload.FileName;
                    string imgExt = imageName.Substring(imageName.LastIndexOf("."));
                    string[] allowedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
                    if (allowedExtensions.Contains(imgExt.ToLower()))
                    {
                        //make sure it's unique... like:
                        imageName = Guid.NewGuid() + imgExt;

                        //OR datetimestamp + bookname
                        //imageName = (DateTime.Now.ToString("yyyyMMddHHmmss") + "_"
                        //    + title.BookTitle).Substring(0, 100);

                        //---Prepare the variables for image service ResizeImage()--
                        //set up the server path for where to upload (folder path only)
                        string folderSavePath = Server.MapPath("~/Content/Images/Uploads/");

                        //convert the uploaded file from HttpPostedFileBase to Image 
                        //(requires System.Drawing namespace)
                        Image convertedImage = Image.FromStream(imageUpload.InputStream);

                        //set max size for full-size image (in pixels)
                        int maxImageSize = 500;

                        //set max size for thumbnail image
                        int maxThumbSize = 100;

                        //----call image service to resize & save
                        ImageServices.ResizeImage(folderSavePath, imageName, convertedImage
                            , maxImageSize, maxThumbSize);
                    }
                    else
                    {
                        //if the user uploads an unacceptable file type, throw exception 
                        //throw new InvalidFileTypeException("Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed");
                        ViewBag.Message = "Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed";
                        return View(ownerAsset);
                    }
                }

                //regardless of whether we had an image upload, update the BookImage
                //property of the new title record before adding it to the DB.
                ViewBag.Message = null;
                ownerAsset.AssetPhoto = imageName;

                #endregion

                ownerAsset.OwnerID = User.Identity.GetUserId();
                ownerAsset.DateAdded = DateTime.UtcNow;
                db.OwnerAssets.Add(ownerAsset);
                db.SaveChanges();
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("AdminIndex");
                }
                else
                {
                return RedirectToAction("Index");
                }
            }

            return View(ownerAsset);
        }

        // GET: OwnerAssets/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            var currentUser = User.Identity.GetUserId();
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets.Where(x => (x.OwnerID == currentUser)), "OwnerAssetID", "AssetName");
            return View(ownerAsset);
        }

        // POST: OwnerAssets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "OwnerAssetID,AssetName,OwnerID,AssetPhoto,SpecialNotes,IsActive,DateAdded")] OwnerAsset ownerAsset, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {

                #region File Upload using Image Service
                string imageName = "noimage.png";//default image filename

                if (imageUpload != null)
                {
                    //process the image upload if it exists...
                    imageName = imageUpload.FileName;
                    string imgExt = imageName.Substring(imageName.LastIndexOf("."));
                    string[] allowedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
                    if (allowedExtensions.Contains(imgExt.ToLower()))
                    {
                        //make sure it's unique... like:
                        imageName = Guid.NewGuid() + imgExt;

                        //OR datetimestamp + bookname
                        //imageName = (DateTime.Now.ToString("yyyyMMddHHmmss") + "_"
                        //    + title.BookTitle).Substring(0, 100);

                        //---Prepare the variables for image service ResizeImage()--
                        //set up the server path for where to upload (folder path only)
                        string folderSavePath = Server.MapPath("~/Content/Images/Uploads/");

                        //convert the uploaded file from HttpPostedFileBase to Image 
                        //(requires System.Drawing namespace)
                        Image convertedImage = Image.FromStream(imageUpload.InputStream);

                        //set max size for full-size image (in pixels)
                        int maxImageSize = 500;

                        //set max size for thumbnail image
                        int maxThumbSize = 100;

                        //----call image service to resize & save
                        ImageServices.ResizeImage(folderSavePath, imageName, convertedImage
                            , maxImageSize, maxThumbSize);
                    }
                    else
                    {
                        //if the user uploads an unacceptable file type, throw exception 
                        //throw new InvalidFileTypeException("Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed");
                        ViewBag.Message = "Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed";
                        return View(ownerAsset);
                    }
                }
                else
                {
                    imageName = ownerAsset.AssetPhoto;
                }

                //regardless of whether we had an image upload, update the BookImage
                //property of the new title record before adding it to the DB.
                ViewBag.Message = null;
                ownerAsset.AssetPhoto = imageName;

                #endregion
                if (User.IsInRole("User"))
                {

ReservationSystem.UI/Views/OwnerAssets/AdminIndex.cshtml
@model IEnumerable<ReservationSystem.DATA.EF.OwnerAsset>

@{
    ViewBag.Title = "ALL TEAMS";
}

<h2>@ViewBag.Title</h2>

<p>
    <a href="@Url.Action("Create","OwnerAssets")"><i class="fa fa-plus-square"></i></a>
    @*@Html.ActionLink("New Reservation", "Create")*@
</p>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.OwnerID)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.SpecialNotes)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>*@
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetName)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.OwnerID)
                </td>*@
                <td>
                    @*@Html.DisplayFor(modelItem => item.AssetPhoto)*@
                    <img src="~/Content/Images/Uploads/t_@item.AssetPhoto"
                         alt="@item.AssetName" />
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.SpecialNotes)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.DateAdded)
                </td>*@
                <td>
                    <a id="fontAwesomeButton" href="@Url.Action("Edit","OwnerAssets", new { id = item.OwnerAssetID })"><i class="far fa-edit"></i></a>
                    <a id="fontAwesomeButton" href="@Url.Action("Details","OwnerAssets",new { id = item.OwnerAssetID})"><i class="fas fa-info"></i></a>
                    <a id="fontAwesomeButton" href="@Url.Action("Delete","OwnerAssets",new { id = item.OwnerAssetID})"><i class="far fa-trash-alt"></i></a>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.OwnerAssetID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.OwnerAssetID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.OwnerAssetID })*@
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
    $(document).ready( function () {
        $('#myTable').DataTable({ responsive: true });
    });
    </script>

}

ReservationSystem.UI/Views/OwnerAssets/Create.cshtml
@model ReservationSystem.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "NEW TEAM";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create","OwnerAssets", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
   <hr />
<div class="row">
    <div class="text-danger">
        @ViewBag.Message
    </div>
</div>

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AssetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })*@


            @*</div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.AssetPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AssetPhoto, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="imageUpload" />
                @Html.ValidationMessageFor(model => model.AssetPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @if (Request.IsAuthenticated && User.IsInRole("Admin")|| Request.IsAuthenticated && User.IsInRole("Employee"))
                {
                    <a href="@Url.Action("AdminIndex","OwnerAssets")"class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>

                }
                else
                {
                    <a href="@Url.Action("Index","OwnerAssets")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
                }

            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReservationSystem.UI/Views/OwnerAssets/Delete.cshtml
@model ReservationSystem.DATA.EF.OwnerAsset

@{
    ViewBag.Title = $"DELETE {Model.AssetName}";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssetPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssetPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @if (Request.IsAuthenticated && User.IsInRole("Admin") || Request.IsAuthenticated && User.IsInRole("Employee"))
            {
                <a href="@Url.Action("AdminIndex","OwnerAssets")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>

            }
            else
            {
                <a href="@Url.Action("Index","OwnerAssets")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
            }


        </div>
    }
</div>

ReservationSystem.UI/Views/OwnerAssets/Details.cshtml
@model ReservationSystem.DATA.EF.OwnerAsset

@{
    ViewBag.Title = $"{Model.AssetName} DETAILS";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <img id="detailsPhoto" src="~/Content/Images/Uploads/@Model.AssetPhoto"
                 alt="@Model.AssetName" />

        </div>
        <div class="col-md-8">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AssetName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AssetName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.OwnerID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OwnerID)
                </dd>

                @*<dt>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </dt>*@

                @*<dd>
                @Html.DisplayFor(model => model.AssetPhoto)
            </dd>*@

                <dt>
                    @Html.DisplayNameFor(model => model.SpecialNotes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SpecialNotes)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded)
                </dd>

            </dl>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href="@Url.Action("Edit","OwnerAssets", new { id = Model.OwnerAssetID })"><input type="button" value="Edit" class="btn btn-warning" /></a>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || Request.IsAuthenticated && User.IsInRole("Employee"))
                    {
                        <a href="@Url.Action("AdminIndex","OwnerAssets")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>

                    }
                    else
                    {
                        <a href="@Url.Action("Index","OwnerAssets")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
                    }

                </div>
            </div>

        </div>

    </div>
</div>

ReservationSystem.UI/Views/OwnerAssets/Edit.cshtml
@model ReservationSystem.DATA.EF.OwnerAsset

@{
    ViewBag.Title = $"Edit {Model.AssetName}";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Edit", "OwnerAssets", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OwnerAssetID)
        @Html.HiddenFor(model =>model.AssetPhoto)
        @Html.HiddenFor(model => model.OwnerID)
        @Html.HiddenFor(model =>model.DateAdded)
        <div class="row">
            <div class="text-danger">
                @ViewBag.Message
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
                </div>
            </div>

        }

        <div class="form-group">
            @Html.LabelFor(model => model.AssetPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AssetPhoto, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="imageUpload" />
                @Html.ValidationMessageFor(model => model.AssetPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || Request.IsAuthenticated && User.IsInRole("Employee"))
                {
                    <a href="@Url.Action("AdminIndex","OwnerAssets")"class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>

                }
                else
                {
                    <a href="@Url.Action("Index","OwnerAssets")"class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
                }

            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReservationSystem.UI/Views/OwnerAssets/Index.cshtml
@model IEnumerable<ReservationSystem.DATA.EF.OwnerAsset>
@{
    ViewBag.Title = "YOUR TEAMS";
}
<h2>@ViewBag.Title</h2>

<p>
    <a href="@Url.Action("Create","OwnerAssets")"><i class="fa fa-plus-square"></i></a>
    @*@Html.ActionLink("New Reservation", "Create")*@
</p>

@if (User.IsInRole("Admin") || User.IsInRole("Employee") || User.IsInRole("User"))
{
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.OwnerID)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpecialNotes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>*@
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)

        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetName)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.OwnerID)
                </td>*@
                <td>
                    @*@Html.DisplayFor(modelItem => item.AssetPhoto)*@
                    <img src="~/Content/Images/Uploads/t_@item.AssetPhoto"
                         alt="@item.AssetName" />

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpecialNotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.DateAdded)
                </td>*@
                @if (User.IsInRole("Admin") || (User.IsInRole("Employee")))
                {
                    <td>
                        <a id="fontAwesomeButton" href="@Url.Action("Edit","OwnerAssets", new { id = item.OwnerAssetID })"><i class="far fa-edit"></i></a>
                        <a id="fontAwesomeButton" href="@Url.Action("Details","OwnerAssets",new { id = item.OwnerAssetID})"><i class="fas fa-info"></i></a>
                        <a id="fontAwesomeButton" href="@Url.Action("Delete","OwnerAssets",new { id = item.OwnerAssetID})"><i class="far fa-trash-alt"></i></a>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.OwnerAssetID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.OwnerAssetID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.OwnerAssetID })*@
                    </td>
                }
                else
                {
                     <td>
                         <a id="fontAwesomeButton" href="@Url.Action("Edit","OwnerAssets", new { id = item.OwnerAssetID })"><i class="far fa-edit"></i></a>
                         <a id="fontAwesomeButton" href="@Url.Action("Details","OwnerAssets",new { id = item.OwnerAssetID})"><i class="fas fa-info"></i></a>
                     </td>
                }
            </tr>

        }
    </tbody>

</table>
}
@section scripts{
    <script>
    $(document).ready( function () {
        $('#myTable').DataTable({ responsive: true });
    });
</script>
    }