ReservationSystem.UI/Controllers/HomeController.cs
using System.Web.Mvc;
using ReservationSystem.DATA.EF;
using System.Data.Entity;
using System.Linq;
using System;
using ReservationSystem.UI.Models;
using System.Net;
using System.Net.Mail;

namespace IdentitySample.Controllers
{
    public class HomeController : Controller
    {
        private ReservationSystemEntities db = new ReservationSystemEntities();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FeaturedLocations()
        {

            return PartialView(db.Locations.Take(4));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }
        public ActionResult Contact()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactFormViewModel contact)
        {
            if (ModelState.IsValid)
            {
                //How to send email:
                //Construct a string value that will represent the 
                //mail message.

                //SET DEFAULT VALUES
                contact.TimeStamp = DateTime.Now;
                //optionally you can hard code your subject (helps with 
                //mail sorting) - Usually this is done when you OMIT the 
                //subject field from the  mail form
                contact.Subject = "You have mail from IntroToMVC";

                string messageContent = $"Name: {contact.Name}<br />Email:" +
                    $"{contact.Email}<br />Subject: {contact.Subject}<br />" +
                    $"<h4>Message</h4> {contact.Message}<br />" +
                    $"TimeStamp: {contact.TimeStamp}";

                //if you wanted them to see their subject, you could
                //change the order of operations and move the hard code
                //of the subject here (you would see their original
                //subject as part of the messageContent variable).

                //Create a MailMessage Object (System.Net.Mail)
                //FROM   
                MailMessage m = new MailMessage("webadmin@krisvargas.com",
                    //TO            Subject,          Body
                    "kvargas981@outlook.com", contact.Subject, messageContent);

                //allow for html body
                m.IsBodyHtml = true;

                //replyto set to reply to the original emailer not your
                //website
                m.ReplyToList.Add(contact.Email);//Respond to the persons
                                                 //email that SENT you a message from your website.

                //CC/BCC
                //m.CC.Add(contact.Email);
                //Carbon Copy all recipients can see each other on the 
                //email

                //BCC is added the same way, BCC is a blind carbon copy
                //and appears as they are the ONLY recipient.

                //Priority
                m.Priority = MailPriority.High;//optional setting

                //Smtp client
                SmtpClient client = new SmtpClient("mail.krisvargas.com");

                //assign client credentials
                client.Credentials = new NetworkCredential("webadmin@krisvargas.com",
                    "P@ssw0rd");

                //send the message
                using (client)
                {
                    try
                    {
                        client.Send(m);
                    }
                    catch
                    {
                        ViewBag.ErrorMessage = "There was an error sending" +
                            " your message.  Please Try again";
                        return View(contact);
                    }
                }//closes the connection on client

                //redirect to the confirmation
                return View("ContactConfirm", contact);
            }
            //if it fails validation return to the form 
            //sending the contact object back to the view
            //to repopulate the form.
            return View(contact);
        }









    }

}

ReservationSystem.UI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationSystem.DATA.EF;
using System.Drawing;
using ReservationSystem.DATA.EF.Services;

namespace ReservationSystem.UI.Controllers
{
    public class LocationsController : Controller
    {
        private ReservationSystemEntities db = new ReservationSystemEntities();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Details/5
      
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles ="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,LocationName,LocationPhoto,Address,City,State,ZipCode,ReservationLimit")] Location location, HttpPostedFileBase imageUpload)
        {
            #region File Upload using Image Service
            string imageName = "noimage.png";//default image filename

            if (imageUpload != null)
            {
                //process the image upload if it exists...
                imageName = imageUpload.FileName;
                string imgExt = imageName.Substring(imageName.LastIndexOf("."));
                string[] allowedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
                if (allowedExtensions.Contains(imgExt.ToLower()))
                {
                    //make sure it's unique... like:
                    imageName = Guid.NewGuid() + imgExt;

                    //OR datetimestamp + bookname
                    //imageName = (DateTime.Now.ToString("yyyyMMddHHmmss") + "_"
                    //    + title.BookTitle).Substring(0, 100);

                    //---Prepare the variables for image service ResizeImage()--
                    //set up the server path for where to upload (folder path only)
                    string folderSavePath = Server.MapPath("~/Content/Images/Uploads/");

                    //convert the uploaded file from HttpPostedFileBase to Image 
                    //(requires System.Drawing namespace)
                    Image convertedImage = Image.FromStream(imageUpload.InputStream);

                    //set max size for full-size image (in pixels)
                    int maxImageSize = 500;

                    //set max size for thumbnail image
                    int maxThumbSize = 100;

                    //----call image service to resize & save
                    ImageServices.ResizeImage(folderSavePath, imageName, convertedImage
                        , maxImageSize, maxThumbSize);
                }
                else
                {
                    //if the user uploads an unacceptable file type, throw exception 
                    //throw new InvalidFileTypeException("Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed");
                    ViewBag.Message = "Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed";
                    return View(location);
                }
            }

            //regardless of whether we had an image upload, update the BookImage
            //property of the new title record before adding it to the DB.
            ViewBag.Message = null;
            location.LocationPhoto = imageName;

            #endregion

            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5        
        [Authorize(Roles ="Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult Edit([Bind(Include = "LocationID,LocationName,LocationPhoto,Address,City,State,ZipCode,ReservationLimit")] Location location, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)

            {
                #region File Upload using Image Service
                string imageName = "noimage.png";//default image filename

                if (imageUpload != null)
                {
                    //process the image upload if it exists...
                    imageName = imageUpload.FileName;
                    string imgExt = imageName.Substring(imageName.LastIndexOf("."));
                    string[] allowedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
                    if (allowedExtensions.Contains(imgExt.ToLower()))
                    {
                        //make sure it's unique... like:
                        imageName = Guid.NewGuid() + imgExt;

                        //OR datetimestamp + bookname
                        //imageName = (DateTime.Now.ToString("yyyyMMddHHmmss") + "_"
                        //    + title.BookTitle).Substring(0, 100);

                        //---Prepare the variables for image service ResizeImage()--
                        //set up the server path for where to upload (folder path only)
                        string folderSavePath = Server.MapPath("~/Content/Images/Uploads/");

                        //convert the uploaded file from HttpPostedFileBase to Image 
                        //(requires System.Drawing namespace)
                        Image convertedImage = Image.FromStream(imageUpload.InputStream);

                        //set max size for full-size image (in pixels)
                        int maxImageSize = 500;

                        //set max size for thumbnail image
                        int maxThumbSize = 100;

                        //----call image service to resize & save
                        ImageServices.ResizeImage(folderSavePath, imageName, convertedImage
                            , maxImageSize, maxThumbSize);
                    }
                    else
                    {
                        //if the user uploads an unacceptable file type, throw exception 
                        //throw new InvalidFileTypeException("Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed");
                        ViewBag.Message = "Invalid File Type Uploaded. Only .png, .jpg, .jpeg, and .gif file types are allowed";
                        return View(location);
                    }
                }
                else
                {
                    imageName = location.LocationPhoto;
                }

                //regardless of whether we had an image upload, update the BookImage
                //property of the new title record before adding it to the DB.
                ViewBag.Message = null;
                location.LocationPhoto = imageName;

                #endregion

                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        [Authorize(Roles ="Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationSystem.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div class="row-fluid">
    <div class="span12">
        <p>Use this area to provide additional information.</p>
    </div>
</div>

ReservationSystem.UI/Views/Home/Contact.cshtml
@model ReservationSystem.UI.Models.ContactFormViewModel

@using (Html.BeginForm())
{
    Layout = null;
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ReservationSystem.UI/Views/Home/ContactConfirm.cshtml
@model ReservationSystem.UI.Models.ContactFormViewModel

@{
    Layout = null;
    ViewBag.Title = "Your Message Has Been Sent";
}

<h2>@ViewBag.Title</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>
</div>

ReservationSystem.UI/Views/Home/FeaturedLocations.cshtml
@model IEnumerable<ReservationSystem.DATA.EF.Location>

@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LocationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
        </tr>
    }

    </table>*@




@foreach (var item in Model)
{
    <div class="col-md-6">
        @*<h3 class="featuredLocationName">@Html.DisplayFor(modelItem => item.LocationName)</h3>*@
        <div class="col-md-12">
            <a href="@Url.Action("Details","Locations", new { id = item.LocationID})">
                <img id="featuredLocationPhoto" src="~/Content/Images/Uploads/@item.LocationPhoto"
                     alt="@item.LocationName" />
            </a>
        </div>
        @*<div class="col-md-12">
            <p>@Html.DisplayFor(modelItem => item.City), @Html.DisplayFor(modelItem => item.State) </p>
        </div>*@
            @*<input type="button" class="btn btn-primary" value="Info"/>*@

    </div>
}

ReservationSystem.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}
<video autoplay muted loop id="myVideo">
    <source src="~/Content/Background/2018 Mid-Season Invitational Group Stage Day 5 Tease.mp4" type="video/mp4">
</video>
<div class="row" id="contentWrapper">
    <div class="col-md-12">
        <h1>Welcome to Team Practice Manager</h1>
        <p>
            We're dedicated and passionate about serving the rapidly expanding eSports scene,
            and our service will allow you to reserve locations for your team practices!
            Our selected facilities offer great equipment to their customers, so no need to bring your own!
            Create an account, add a team to your account, and reserve a location for a practice session today!
            If you need to contact the site admins, just click where it says "Contact Us" and send us mail directly from the site!
        </p>
        <div class="col-md-6">
            <h2 onclick="ShowHide()">Featured Locations</h2>
        </div>
        <div class="col-md-6">
            <h2 onclick="ShowHideContact()">Contact Us</h2>
        </div>

        <div id="content" class="col-md-6">
            @Html.Action("FeaturedLocations", "Home")
        </div>
        <div id="contact" class="col-md-6">
            @Html.Action("Contact", "Home")
        </div>
    </div>
</div>

@section scripts{
    <script>
        function ShowHide() {
            var x = document.getElementById('content');
            if (x.style.visibility === 'visible') {
                x.style.visibility = 'hidden';
            }
            else {
                x.style.visibility = 'visible';
            }
        }
    </script>
    <script>
        function ShowHideContact() {
            var x = document.getElementById('contact');
            if (x.style.visibility === 'visible') {
                x.style.visibility = 'hidden';
            }
            else {
                x.style.visibility = 'visible';
            }
        }
    </script>



}