ReservationSystem.UI/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationSystem.DATA.EF;
using Microsoft.AspNet.Identity;
using System.Drawing;
using ReservationSystem.DATA.EF.Services;

namespace ReservationSystem.UI.Controllers
{
    public class ReservationsController : Controller
    {
        private ReservationSystemEntities db = new ReservationSystemEntities();

        // GET: Reservations
        [Authorize]
        public ActionResult Index()
        {

            var currentUser = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || User.IsInRole("Employee"))
            {
                var reservations = db.Reservations.Include(r => r.Location).Include(r => r.OwnerAsset);
                return View(reservations.ToList());
            }
            else
            {
                var reservations = db.Reservations.Include(r => r.Location).Include(r => r.OwnerAsset).Where(x => x.OwnerAsset.OwnerID == currentUser);
                return View(reservations.ToList());

            }
        }

        // GET: Reservations/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        [Authorize(Roles ="Admin, User")]
        public ActionResult Create()
        {
            if (Request.IsAuthenticated && User.IsInRole("User"))
            {
                var currentUser = User.Identity.GetUserId();
                ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
                ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets.Where(x => (x.OwnerID == currentUser)), "OwnerAssetID", "AssetName");
            }
            if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
                ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName");
            }
            return View();
        }


        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ReservationID,LocationID,ReservationDate,OwnerAssetID")] Reservation reservation)
        {


            Location desiredLocation = db.Locations.Where(x => x.LocationID == reservation.LocationID).Single();
            DateTime desiredDate = reservation.ReservationDate;
            int resLimit = desiredLocation.ReservationLimit;
            int currentReservations = db.Reservations.Where(x => (x.LocationID == desiredLocation.LocationID) && (x.ReservationDate == desiredDate)).Count();
            var currentUser = User.Identity.GetUserId();
            int currentUserReservations = db.Reservations.Where(x => (x.OwnerAssetID == reservation.OwnerAssetID) && (x.ReservationDate == desiredDate)).Count();
            if (ModelState.IsValid)
            {
                if (currentReservations < resLimit && !User.IsInRole("Admin"))
                {
                    if (currentUserReservations == 0)
                    {
                        db.Reservations.Add(reservation);
                        db.SaveChanges();
                        ViewBag.Message = null;
                        return RedirectToAction("Index");
                    }
                    ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
                    ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName", reservation.OwnerAssetID);

                    ViewBag.Message = "This User has already been booked for this date";

                    return View(reservation);

                }
                if (currentUserReservations == 0 && User.IsInRole("Admin"))
                {
                    db.Reservations.Add(reservation);
                    db.SaveChanges();
                    ViewBag.Message = null;
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
                    ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName", reservation.OwnerAssetID);
                    ViewBag.Message = "This location is overbooked";
                    return View(reservation);

                }

            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName", reservation.OwnerAssetID);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Edit(int? id)
        {
            var currentUser = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName", reservation.OwnerAssetID);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Edit([Bind(Include = "ReservationID,LocationID,ReservationDate,OwnerAssetID")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetName", reservation.OwnerAssetID);


            return View(reservation);
        }

        // GET: Reservations/Delete/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationSystem.UI/Views/Reservations/Create.cshtml
@model ReservationSystem.DATA.EF.Reservation

@{
    ViewBag.Title = "MAKE YOUR RESERVATION";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="row">
        <div class="text-danger">
            @ViewBag.Message
        </div>
    </div>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label col-md-2" })


            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", @id = "datepicker" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                @Html.ValidationMessageFor(model => model.ReservationDate)
            </div>
        </div>


        @*<div class="form-group">
                <div class="col-md-10">
                    <input type="text" id="datepicker" />
                </div>
            </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.OwnerAssetID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerAssetID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerAssetID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Reserve" class="btn btn-success" />
                @*<input type="submit" value="Create" class="btn btn-default" />*@
                <a href="@Url.Action("Index","Home")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>

            </div>
        </div>
    </div>
}

<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#datepicker").datepicker({
                minDate: 0,
                maxDate: '+6m'
            });
        });
    </script>
}

ReservationSystem.UI/Views/Reservations/Delete.cshtml
@model ReservationSystem.DATA.EF.Reservation

@{
    ViewBag.Title = $"DELETE RESERVATION ON {Model.ReservationDate} FOR {Model.Location.LocationName}";
}

<h2>@ViewBag.Title</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerAsset.AssetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerAsset.AssetName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a href="@Url.Action("Index","Reservations")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
        </div>
    }
</div>

ReservationSystem.UI/Views/Reservations/Details.cshtml
@model ReservationSystem.DATA.EF.Reservation

@{
    ViewBag.Title = $"{Model.ReservationDate} for {Model.Location.LocationName} Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerAsset.AssetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerAsset.AssetName)
        </dd>

    </dl>
    <div class="form-group">
        <a href="@Url.Action("Edit","Reservations", new { id = Model.ReservationID})"><input type="button" value="Edit" class="btn btn-warning" /></a>
        <a href="@Url.Action("Index","Reservations")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
    </div>


</div>

ReservationSystem.UI/Views/Reservations/Edit.cshtml
@model ReservationSystem.DATA.EF.Reservation

@{
    ViewBag.Title = $"EDIT RESERVATION FOR {Model.Location.LocationName}";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReservationID)
        @Html.HiddenFor(model =>model.ReservationDate)

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerAssetID, "OwnerAssetID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerAssetID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerAssetID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a href="@Url.Action("Index","Reservations")" class="btn btn-primary"><i class="fas fa-undo-alt"></i></a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReservationSystem.UI/Views/Reservations/Index.cshtml
@model IEnumerable<ReservationSystem.DATA.EF.Reservation>

@{
    ViewBag.Title = "RESERVATIONS";
}

<h2>@ViewBag.Title</h2>
@if (User.IsInRole("Admin") || User.IsInRole("User"))
{
    <p>
        <a href="@Url.Action("Create","Reservations")"><i class="fa fa-plus-square"></i></a>
        @*@Html.ActionLink("New Reservation", "Create")*@
    </p>
}
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.LocationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerAsset.AssetName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ReservationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.LocationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerAsset.AssetName)
                </td>
                @if (User.IsInRole("Admin") || (User.IsInRole("Employee")))
                {
                    <td>
                        <a id="fontAwesomeButton" href="@Url.Action("Edit","Reservations", new { id = item.ReservationID })"><i class="far fa-edit"></i></a>
                        <a id="fontAwesomeButton" href="@Url.Action("Details","Reservations",new { id = item.ReservationID})"><i class="fas fa-info"></i></a>
                        <a id="fontAwesomeButton" href="@Url.Action("Delete","Reservations",new { id = item.ReservationID})"><i class="far fa-trash-alt"></i></a>
                        @*@Html.ActionLink("Details", "Details", new { id = item.ReservationID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ReservationID })*@
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ReservationID }) |*@


                    </td>

                }
                else
                {
                    <td>
                        <a href="@Url.Action("Details","Reservations",new { id = item.ReservationID})"><i class="fas fa-info"></i></a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
@section scripts {
    <script>
    $(document).ready( function () {
        $('#myTable').DataTable({responsive:true});
    });
</script>

    }